version: "3.8"

services:
  service1:
    build: ./service1
    ports:
      - "8199:8199"
    volumes:
      - ./vstorage:/app/vstorage
    depends_on:
      - service2
      - storage
    networks:
      - backend

  service2:
    build: ./service2
    volumes:
      - ./vstorage:/app/vstorage
    networks:
      - backend

  storage:
    build: ./storage
    volumes:
      - storage_data:/app/data
    networks:
      - backend

volumes:
  storage_data:

networks:
  backend:
    driver: bridge